name: Best Baby Products
favicon: null
layout_spectrum: 0.001556426053866744
typography_spectrum: 0.534024793189019
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9987946313340217
  lightness: 0.12180804507806897
  saturation: 0.8504851108882576
  rhythmicContrast: 0.8390305240172893
purpose: []
