name: Best Baby Products
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6255
title: Best Baby Products
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8125
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
